/*!
 * Copyright (c) 2020 Digital Bazaar, Inc. All rights reserved.
 */
export const mockKey = {
  type: 'Ed25519VerificationKey2020',
  publicKeyMultibase: 'zEYJrMxWigf9boyeJMTRN4Ern8DJMoCXaLK77pzQmxVjf',
  privateKeyMultibase: 'z4E7Q4neNHwv3pXUNzUjzc6TTYspqn9Aw6vakpRKpbVrCzwKWD4hQ' +
    'DHnxuhfrTaMjnR8BTp9NeUvJiwJoSUM6xHAZ'
};

// this was generated by the node key generator
export const mockNodeKey = {
  type: 'Ed25519VerificationKey2020',
  publicKeyMultibase: 'z7CQPb6yshko363CVmjy4cGViE3vauqDfrJbfB1kmJ6Eb',
  privateKeyMultibase: 'z5PHLJ46vQHSiYR3cSWzXrh5BVgEmTty5BB7xkau3M3aJ' +
    '2v1szyJH6CKK3LVyuWATD5DAFpEuKViu4Mad9uFxNBvo',
  // this signature was produced by a key made by node's crypto functions
  signature: '5exHkpes9ZSLXJoUuAM81s9Z13DwzJYL5ekYMpi7buhSVL29qA3QsVg7' +
    'xQqQabAFXjEqDJ1yJPFYdmgPBhpDbB1o',
  data: 'node key test'
};

export const seed =
  '8c2114a150a16209c653817acc7f3e7e9c6c6290ae93d6689cbd61bb038cd31b';
